// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: endpoints/role.proto

package endpoint

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PermissionInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	UpdateTime           string   `protobuf:"bytes,2,opt,name=update_time,json=updateTime,proto3" json:"updateTime" valid:"required"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"createTime" valid:"required"`
	Name                 *string  `protobuf:"bytes,4,opt,name=name,proto3,customtype=string" json:"name,omitempty"`
	EnableAuth           bool     `protobuf:"varint,5,opt,name=enable_auth,json=enableAuth,proto3" json:"enableAuth,omitempty"`
	ParentId             *string  `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3,customtype=string" json:"parentId,omitempty"`
	Description          string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionInfo) Reset()         { *m = PermissionInfo{} }
func (m *PermissionInfo) String() string { return proto.CompactTextString(m) }
func (*PermissionInfo) ProtoMessage()    {}
func (*PermissionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64721c8ef00ce76, []int{0}
}
func (m *PermissionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionInfo.Unmarshal(m, b)
}
func (m *PermissionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionInfo.Marshal(b, m, deterministic)
}
func (m *PermissionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionInfo.Merge(m, src)
}
func (m *PermissionInfo) XXX_Size() int {
	return xxx_messageInfo_PermissionInfo.Size(m)
}
func (m *PermissionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionInfo proto.InternalMessageInfo

func (m *PermissionInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PermissionInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *PermissionInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *PermissionInfo) GetEnableAuth() bool {
	if m != nil {
		return m.EnableAuth
	}
	return false
}

func (m *PermissionInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type RoleInfo struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	UpdateTime           string            `protobuf:"bytes,2,opt,name=update_time,json=updateTime,proto3" json:"updateTime" valid:"required"`
	CreateTime           string            `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"createTime" valid:"required"`
	Name                 string            `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	Describe             string            `protobuf:"bytes,5,opt,name=describe,proto3" json:"describe,omitempty"`
	Permission           []*PermissionInfo `protobuf:"bytes,6,rep,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RoleInfo) Reset()         { *m = RoleInfo{} }
func (m *RoleInfo) String() string { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()    {}
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64721c8ef00ce76, []int{1}
}
func (m *RoleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleInfo.Unmarshal(m, b)
}
func (m *RoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleInfo.Marshal(b, m, deterministic)
}
func (m *RoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleInfo.Merge(m, src)
}
func (m *RoleInfo) XXX_Size() int {
	return xxx_messageInfo_RoleInfo.Size(m)
}
func (m *RoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleInfo proto.InternalMessageInfo

func (m *RoleInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoleInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *RoleInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *RoleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleInfo) GetDescribe() string {
	if m != nil {
		return m.Describe
	}
	return ""
}

func (m *RoleInfo) GetPermission() []*PermissionInfo {
	if m != nil {
		return m.Permission
	}
	return nil
}

type GetRolesRequest struct {
	BaseListRequest      `protobuf:"bytes,1,opt,name=base_list_request,json=baseListRequest,proto3,embedded=base_list_request" json:",omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesRequest) Reset()         { *m = GetRolesRequest{} }
func (m *GetRolesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRolesRequest) ProtoMessage()    {}
func (*GetRolesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64721c8ef00ce76, []int{2}
}
func (m *GetRolesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesRequest.Unmarshal(m, b)
}
func (m *GetRolesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesRequest.Marshal(b, m, deterministic)
}
func (m *GetRolesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesRequest.Merge(m, src)
}
func (m *GetRolesRequest) XXX_Size() int {
	return xxx_messageInfo_GetRolesRequest.Size(m)
}
func (m *GetRolesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesRequest proto.InternalMessageInfo

type GetRolesResponse struct {
	BaseListResponse     `protobuf:"bytes,1,opt,name=base_list_response,json=baseListResponse,proto3,embedded=base_list_response" json:",omitempty"`
	Data                 []*RoleInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRolesResponse) Reset()         { *m = GetRolesResponse{} }
func (m *GetRolesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRolesResponse) ProtoMessage()    {}
func (*GetRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64721c8ef00ce76, []int{3}
}
func (m *GetRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesResponse.Unmarshal(m, b)
}
func (m *GetRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesResponse.Marshal(b, m, deterministic)
}
func (m *GetRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesResponse.Merge(m, src)
}
func (m *GetRolesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRolesResponse.Size(m)
}
func (m *GetRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesResponse proto.InternalMessageInfo

func (m *GetRolesResponse) GetData() []*RoleInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateRoleRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name" valid:"required"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Permission           []string `protobuf:"bytes,3,rep,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleRequest) Reset()         { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()    {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64721c8ef00ce76, []int{4}
}
func (m *CreateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleRequest.Unmarshal(m, b)
}
func (m *CreateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleRequest.Merge(m, src)
}
func (m *CreateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoleRequest.Size(m)
}
func (m *CreateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleRequest proto.InternalMessageInfo

func (m *CreateRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRoleRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateRoleRequest) GetPermission() []string {
	if m != nil {
		return m.Permission
	}
	return nil
}

type UpdateRoleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name" valid:"required"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Permission           []string `protobuf:"bytes,4,rep,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleRequest) Reset()         { *m = UpdateRoleRequest{} }
func (m *UpdateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleRequest) ProtoMessage()    {}
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64721c8ef00ce76, []int{5}
}
func (m *UpdateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleRequest.Unmarshal(m, b)
}
func (m *UpdateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleRequest.Merge(m, src)
}
func (m *UpdateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleRequest.Size(m)
}
func (m *UpdateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleRequest proto.InternalMessageInfo

func (m *UpdateRoleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRoleRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateRoleRequest) GetPermission() []string {
	if m != nil {
		return m.Permission
	}
	return nil
}

type DeleteRoleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoleRequest) Reset()         { *m = DeleteRoleRequest{} }
func (m *DeleteRoleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRoleRequest) ProtoMessage()    {}
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64721c8ef00ce76, []int{6}
}
func (m *DeleteRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoleRequest.Unmarshal(m, b)
}
func (m *DeleteRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoleRequest.Merge(m, src)
}
func (m *DeleteRoleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRoleRequest.Size(m)
}
func (m *DeleteRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoleRequest proto.InternalMessageInfo

func (m *DeleteRoleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPermissionsRequest struct {
	BaseListRequest      `protobuf:"bytes,1,opt,name=base_list_request,json=baseListRequest,proto3,embedded=base_list_request" json:",omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPermissionsRequest) Reset()         { *m = GetPermissionsRequest{} }
func (m *GetPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPermissionsRequest) ProtoMessage()    {}
func (*GetPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64721c8ef00ce76, []int{7}
}
func (m *GetPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionsRequest.Unmarshal(m, b)
}
func (m *GetPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionsRequest.Marshal(b, m, deterministic)
}
func (m *GetPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionsRequest.Merge(m, src)
}
func (m *GetPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPermissionsRequest.Size(m)
}
func (m *GetPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionsRequest proto.InternalMessageInfo

type GetPermissionsResponse struct {
	BaseListResponse     `protobuf:"bytes,1,opt,name=base_list_response,json=baseListResponse,proto3,embedded=base_list_response" json:",omitempty"`
	Data                 []*PermissionInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetPermissionsResponse) Reset()         { *m = GetPermissionsResponse{} }
func (m *GetPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPermissionsResponse) ProtoMessage()    {}
func (*GetPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64721c8ef00ce76, []int{8}
}
func (m *GetPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionsResponse.Unmarshal(m, b)
}
func (m *GetPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionsResponse.Marshal(b, m, deterministic)
}
func (m *GetPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionsResponse.Merge(m, src)
}
func (m *GetPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPermissionsResponse.Size(m)
}
func (m *GetPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionsResponse proto.InternalMessageInfo

func (m *GetPermissionsResponse) GetData() []*PermissionInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PermissionInfo)(nil), "fuck_web.endpoint.PermissionInfo")
	proto.RegisterType((*RoleInfo)(nil), "fuck_web.endpoint.RoleInfo")
	proto.RegisterType((*GetRolesRequest)(nil), "fuck_web.endpoint.GetRolesRequest")
	proto.RegisterType((*GetRolesResponse)(nil), "fuck_web.endpoint.GetRolesResponse")
	proto.RegisterType((*CreateRoleRequest)(nil), "fuck_web.endpoint.CreateRoleRequest")
	proto.RegisterType((*UpdateRoleRequest)(nil), "fuck_web.endpoint.UpdateRoleRequest")
	proto.RegisterType((*DeleteRoleRequest)(nil), "fuck_web.endpoint.DeleteRoleRequest")
	proto.RegisterType((*GetPermissionsRequest)(nil), "fuck_web.endpoint.GetPermissionsRequest")
	proto.RegisterType((*GetPermissionsResponse)(nil), "fuck_web.endpoint.GetPermissionsResponse")
}

func init() { proto.RegisterFile("endpoints/role.proto", fileDescriptor_b64721c8ef00ce76) }

var fileDescriptor_b64721c8ef00ce76 = []byte{
	// 642 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0x4d, 0x4f, 0xdb, 0x40,
	0x10, 0xc5, 0x4e, 0x9a, 0x26, 0x13, 0xa9, 0x90, 0x15, 0x20, 0x8b, 0x22, 0x9c, 0xba, 0x97, 0x1c,
	0x20, 0xae, 0xa8, 0x50, 0xd5, 0x56, 0x3d, 0x10, 0x90, 0x10, 0x52, 0xab, 0x22, 0xab, 0xbd, 0xf4,
	0x12, 0xd9, 0xd9, 0x21, 0xac, 0x88, 0xbd, 0xc6, 0xbb, 0x2e, 0xe2, 0xd4, 0x23, 0xff, 0xa6, 0xe7,
	0xaa, 0xc7, 0x9e, 0x7a, 0xec, 0xb9, 0x07, 0xff, 0x80, 0x1c, 0xf9, 0x05, 0x95, 0xd7, 0x31, 0xb1,
	0x03, 0xf4, 0x53, 0x42, 0xea, 0x6d, 0xf7, 0xcd, 0xcc, 0x9b, 0xf1, 0xbc, 0xb7, 0x32, 0x2c, 0x62,
	0x40, 0x43, 0xce, 0x02, 0x29, 0xec, 0x88, 0x8f, 0xb0, 0x1b, 0x46, 0x5c, 0x72, 0xd2, 0x3a, 0x8c,
	0x07, 0xc7, 0xfd, 0x53, 0xf4, 0xba, 0x79, 0x78, 0x65, 0x71, 0xc8, 0x87, 0x5c, 0x45, 0xed, 0xf4,
	0x94, 0x25, 0xae, 0x14, 0xca, 0x3d, 0x57, 0x4c, 0xca, 0xad, 0xf3, 0x0a, 0xdc, 0x3b, 0xc0, 0xc8,
	0x67, 0x42, 0x30, 0x1e, 0xec, 0x07, 0x87, 0x9c, 0xd8, 0xa0, 0x33, 0x6a, 0x68, 0x6d, 0xad, 0xd3,
	0xe8, 0x99, 0xe3, 0xc4, 0xd4, 0x19, 0xbd, 0x48, 0xcc, 0xa5, 0xf7, 0xee, 0x88, 0xd1, 0x67, 0x56,
	0x84, 0x27, 0x31, 0x8b, 0x90, 0xae, 0xc7, 0x31, 0xa3, 0x96, 0xa3, 0x33, 0x4a, 0x76, 0xa0, 0x19,
	0x87, 0xd4, 0x95, 0xd8, 0x97, 0xcc, 0x47, 0x43, 0x57, 0x95, 0xd6, 0x38, 0x31, 0x21, 0x83, 0xdf,
	0x30, 0x1f, 0x2f, 0x12, 0x73, 0x61, 0x86, 0xc1, 0x72, 0x0a, 0xf1, 0x94, 0x64, 0x10, 0xe1, 0x25,
	0x49, 0x65, 0x4a, 0x92, 0xc1, 0x37, 0x93, 0x4c, 0xe3, 0x64, 0x0d, 0xaa, 0x81, 0xeb, 0xa3, 0x51,
	0x55, 0xd5, 0xf0, 0x3d, 0x31, 0x6b, 0x42, 0x46, 0x2c, 0x18, 0x3a, 0x0a, 0x27, 0x4f, 0xa1, 0x89,
	0x81, 0xeb, 0x8d, 0xb0, 0xef, 0xc6, 0xf2, 0xc8, 0xb8, 0xd3, 0xd6, 0x3a, 0xf5, 0x9e, 0x31, 0x4e,
	0xcc, 0xc5, 0x0c, 0xde, 0x8e, 0xe5, 0xd1, 0x3a, 0xf7, 0x99, 0x44, 0x3f, 0x94, 0x67, 0x0e, 0x4c,
	0x51, 0xf2, 0x02, 0x1a, 0xa1, 0x1b, 0x61, 0x20, 0xfb, 0x8c, 0x1a, 0x35, 0xc5, 0xdf, 0x9e, 0xf2,
	0x8f, 0x13, 0x93, 0x64, 0xe1, 0x7d, 0x5a, 0x20, 0xa8, 0xe7, 0x18, 0x69, 0x43, 0x93, 0xa2, 0x18,
	0x44, 0x2c, 0x94, 0x8c, 0x07, 0xc6, 0xdd, 0x94, 0xc0, 0x29, 0x42, 0xd6, 0x17, 0x1d, 0xea, 0x0e,
	0x1f, 0xe1, 0xff, 0xae, 0xc1, 0x6a, 0x49, 0x83, 0xfa, 0x38, 0x31, 0xd5, 0x7d, 0xa2, 0xc0, 0x0a,
	0xd4, 0xb3, 0x8f, 0xf6, 0x50, 0xad, 0xbf, 0xe1, 0x5c, 0xde, 0xc9, 0x36, 0x40, 0x78, 0x69, 0x45,
	0xa3, 0xd6, 0xae, 0x74, 0x9a, 0x9b, 0x0f, 0xba, 0x57, 0xfc, 0xdd, 0x2d, 0xfb, 0xd5, 0x29, 0x14,
	0x59, 0x67, 0x30, 0xbf, 0x87, 0x32, 0x5d, 0xa3, 0x70, 0xf0, 0x24, 0x46, 0x21, 0xc9, 0x21, 0xb4,
	0x52, 0xbf, 0xf7, 0x47, 0x4c, 0xc8, 0x7e, 0x94, 0x81, 0x6a, 0xb3, 0xcd, 0x4d, 0xeb, 0x1a, 0xf2,
	0x9e, 0x2b, 0xf0, 0x25, 0x13, 0x72, 0x52, 0xde, 0x5b, 0xfe, 0x9a, 0x98, 0x73, 0xdf, 0x12, 0x53,
	0x4b, 0xd7, 0x50, 0x90, 0x76, 0xde, 0x2b, 0x27, 0x5a, 0x1f, 0x35, 0x58, 0x98, 0xf6, 0x16, 0x21,
	0x0f, 0x04, 0x12, 0x06, 0xa4, 0xd8, 0x3c, 0x43, 0x27, 0xdd, 0x1f, 0xfe, 0xb4, 0x7b, 0x96, 0x7a,
	0x63, 0xfb, 0x05, 0x6f, 0x26, 0x93, 0xd8, 0x50, 0xa5, 0xae, 0x74, 0x0d, 0x5d, 0xed, 0xed, 0xfe,
	0x35, 0xe4, 0xb9, 0xbb, 0x1c, 0x95, 0x68, 0x9d, 0x6b, 0xd0, 0xda, 0x51, 0xba, 0xa5, 0x81, 0x7c,
	0x5d, 0x8f, 0x26, 0xf2, 0x65, 0xde, 0x5b, 0xcd, 0xe5, 0xbb, 0x56, 0xf6, 0x4c, 0xd2, 0x19, 0x6b,
	0xeb, 0x57, 0xac, 0x4d, 0xd6, 0x4a, 0xc2, 0x56, 0xda, 0x95, 0x4e, 0xa3, 0xa4, 0xda, 0x27, 0x0d,
	0x5a, 0x6f, 0x95, 0x0d, 0x8b, 0x93, 0xfc, 0xf1, 0x1b, 0xc8, 0x47, 0xd7, 0xff, 0x76, 0xf4, 0xca,
	0xaf, 0x46, 0xaf, 0x5e, 0x19, 0x7d, 0x17, 0x5a, 0xbb, 0x38, 0xc2, 0x7f, 0x9b, 0xdc, 0xfa, 0x00,
	0x4b, 0x7b, 0x28, 0xa7, 0xbe, 0xbe, 0x75, 0xf3, 0x7e, 0xd6, 0x60, 0x79, 0x76, 0x82, 0xdb, 0xb7,
	0xf0, 0x56, 0xc9, 0xc2, 0xbf, 0xf1, 0xf4, 0x55, 0x7a, 0xef, 0xc9, 0xbb, 0xad, 0x21, 0x93, 0x47,
	0xb1, 0xd7, 0x1d, 0x70, 0xdf, 0x7e, 0xc5, 0x06, 0x11, 0x7f, 0x1d, 0x8a, 0x8d, 0x41, 0x60, 0xa7,
	0x04, 0x1b, 0xa7, 0xe8, 0xd9, 0xe1, 0xf1, 0xd0, 0xce, 0x49, 0x9e, 0xe7, 0x87, 0x83, 0x39, 0xaf,
	0xa6, 0xfe, 0x82, 0x8f, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x4a, 0x7f, 0x15, 0x5c, 0x07,
	0x00, 0x00,
}
