// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: endpoints/users.proto

package endpoint

import (
	fmt "fmt"
	_ "github.com/MicroOps-cn/fuck-web/pkg/service/models"
	github_com_MicroOps_cn_fuck_web_pkg_service_models "github.com/MicroOps-cn/fuck-web/pkg/service/models"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	Id                   string                                                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	Username             string                                                                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username" valid:"required,matches(^[-_A-Za-z0-9]+$)"`
	Status               github_com_MicroOps_cn_fuck_web_pkg_service_models.UserMeta_UserStatus `protobuf:"varint,3,opt,name=status,proto3,enum=fuck_web.service.models.UserMeta_UserStatus,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.UserMeta_UserStatus" json:"status"`
	Email                string                                                                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	FullName             string                                                                 `protobuf:"bytes,6,opt,name=full_name,json=fullName,proto3" json:"fullName,omitempty"`
	Avatar               string                                                                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	PhoneNumber          string                                                                 `protobuf:"bytes,8,opt,name=phone_number,json=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Role                 string                                                                 `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`
	RoleId               string                                                                 `protobuf:"bytes,10,opt,name=role_id,json=roleId,proto3" json:"roleId,omitempty"`
	LoginTime            string                                                                 `protobuf:"bytes,11,opt,name=login_time,json=loginTime,proto3" json:"loginTime,omitempty"`
	UpdateTime           string                                                                 `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"updateTime" valid:"required"`
	CreateTime           string                                                                 `protobuf:"bytes,13,opt,name=create_time,json=createTime,proto3" json:"createTime" valid:"required"`
	IsDelete             bool                                                                   `protobuf:"varint,14,opt,name=is_delete,json=isDelete,proto3" json:"isDelete" valid:"required"`
	ExtendedData         *github_com_MicroOps_cn_fuck_web_pkg_service_models.UserExt            `protobuf:"bytes,15,opt,name=extended_data,json=extendedData,proto3,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.UserExt" json:"extendedData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                               `json:"-"`
	XXX_unrecognized     []byte                                                                 `json:"-"`
	XXX_sizecache        int32                                                                  `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{0}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UserInfo) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *UserInfo) GetLoginTime() string {
	if m != nil {
		return m.LoginTime
	}
	return ""
}

func (m *UserInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *UserInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *UserInfo) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

type GetUsersRequest struct {
	BaseListRequest      `protobuf:"bytes,1,opt,name=base_list_request,json=baseListRequest,proto3,embedded=base_list_request" json:",omitempty"`
	Status               *github_com_MicroOps_cn_fuck_web_pkg_service_models.UserMeta_UserStatus `protobuf:"varint,4,opt,name=status,proto3,enum=fuck_web.service.models.UserMeta_UserStatus,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.UserMeta_UserStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                `json:"-"`
	XXX_unrecognized     []byte                                                                  `json:"-"`
	XXX_sizecache        int32                                                                   `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{1}
}
func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

type GetUserResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,embedded=base_response" json:",omitempty"`
	Data                 *UserInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{2}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetData() *UserInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetUsersResponse struct {
	BaseListResponse     `protobuf:"bytes,1,opt,name=base_list_response,json=baseListResponse,proto3,embedded=base_list_response" json:",omitempty"`
	Data                 []*UserInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{3}
}
func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetData() []*UserInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type PatchUserRequest struct {
	Id                   string                                                                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" valid:"required,uuid"`
	Status               *github_com_MicroOps_cn_fuck_web_pkg_service_models.UserMeta_UserStatus `protobuf:"varint,2,opt,name=status,proto3,enum=fuck_web.service.models.UserMeta_UserStatus,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.UserMeta_UserStatus" json:"status,omitempty"`
	IsDelete             *bool                                                                   `protobuf:"varint,3,opt,name=is_delete,json=isDelete,proto3,customtype=bool" json:"isDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                `json:"-"`
	XXX_unrecognized     []byte                                                                  `json:"-"`
	XXX_sizecache        int32                                                                   `json:"-"`
}

func (m *PatchUserRequest) Reset()         { *m = PatchUserRequest{} }
func (m *PatchUserRequest) String() string { return proto.CompactTextString(m) }
func (*PatchUserRequest) ProtoMessage()    {}
func (*PatchUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{4}
}
func (m *PatchUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchUserRequest.Unmarshal(m, b)
}
func (m *PatchUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchUserRequest.Marshal(b, m, deterministic)
}
func (m *PatchUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchUserRequest.Merge(m, src)
}
func (m *PatchUserRequest) XXX_Size() int {
	return xxx_messageInfo_PatchUserRequest.Size(m)
}
func (m *PatchUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchUserRequest proto.InternalMessageInfo

func (m *PatchUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ResetUserPasswordRequest struct {
	Token                *github_com_MicroOps_cn_fuck_web_pkg_service_models.Secret `protobuf:"bytes,1,opt,name=token,proto3,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.Secret" json:"token,omitempty"`
	OldPassword          *github_com_MicroOps_cn_fuck_web_pkg_service_models.Secret `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.Secret" json:"oldPassword,omitempty"`
	UserId               string                                                     `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"userId" valid:"optional,uuid"`
	NewPassword          *github_com_MicroOps_cn_fuck_web_pkg_service_models.Secret `protobuf:"bytes,5,opt,name=new_password,json=newPassword,proto3,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.Secret" json:"newPassword" valid:"required"`
	Username             string                                                     `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty" valid:"optional,matches(^[-_A-Za-z0-9]+$)"`
	XXX_NoUnkeyedLiteral struct{}                                                   `json:"-"`
	XXX_unrecognized     []byte                                                     `json:"-"`
	XXX_sizecache        int32                                                      `json:"-"`
}

func (m *ResetUserPasswordRequest) Reset()         { *m = ResetUserPasswordRequest{} }
func (m *ResetUserPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetUserPasswordRequest) ProtoMessage()    {}
func (*ResetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{5}
}
func (m *ResetUserPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetUserPasswordRequest.Unmarshal(m, b)
}
func (m *ResetUserPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetUserPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetUserPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetUserPasswordRequest.Merge(m, src)
}
func (m *ResetUserPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetUserPasswordRequest.Size(m)
}
func (m *ResetUserPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetUserPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetUserPasswordRequest proto.InternalMessageInfo

func (m *ResetUserPasswordRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ResetUserPasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ForgotUserPasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username" valid:"required,matches(^[-_A-Za-z0-9]+$)"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotUserPasswordRequest) Reset()         { *m = ForgotUserPasswordRequest{} }
func (m *ForgotUserPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotUserPasswordRequest) ProtoMessage()    {}
func (*ForgotUserPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{6}
}
func (m *ForgotUserPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotUserPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotUserPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotUserPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotUserPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotUserPasswordRequest.Merge(m, src)
}
func (m *ForgotUserPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotUserPasswordRequest.Size(m)
}
func (m *ForgotUserPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotUserPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotUserPasswordRequest proto.InternalMessageInfo

func (m *ForgotUserPasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ForgotUserPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type DeleteUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{7}
}
func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateUserRequest struct {
	Id                   string                                                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	Username             string                                                                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username" valid:"required,matches(^[-_A-Za-z0-9]+$)"`
	Status               github_com_MicroOps_cn_fuck_web_pkg_service_models.UserMeta_UserStatus `protobuf:"varint,3,opt,name=status,proto3,enum=fuck_web.service.models.UserMeta_UserStatus,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.UserMeta_UserStatus" json:"status,omitempty"`
	Email                string                                                                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	FullName             string                                                                 `protobuf:"bytes,6,opt,name=full_name,json=fullName,proto3" json:"fullName,omitempty"`
	Avatar               string                                                                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	PhoneNumber          string                                                                 `protobuf:"bytes,8,opt,name=phone_number,json=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	IsDelete             bool                                                                   `protobuf:"varint,9,opt,name=is_delete,json=isDelete,proto3" json:"isDelete,omitempty"`
	RoleId               string                                                                 `protobuf:"bytes,10,opt,name=role_id,json=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                               `json:"-"`
	XXX_unrecognized     []byte                                                                 `json:"-"`
	XXX_sizecache        int32                                                                  `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{8}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UpdateUserRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UpdateUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UpdateUserRequest) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *UpdateUserRequest) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type CreateUserRequest struct {
	Username             string                                                                  `protobuf:"bytes,1,opt,name=username,proto3" json:"username" valid:"required,matches(^[-_A-Za-z0-9]+$)"`
	Email                string                                                                  `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName             string                                                                  `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"fullName,omitempty"`
	Avatar               string                                                                  `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	PhoneNumber          string                                                                  `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Status               *github_com_MicroOps_cn_fuck_web_pkg_service_models.UserMeta_UserStatus `protobuf:"varint,7,opt,name=status,proto3,enum=fuck_web.service.models.UserMeta_UserStatus,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.UserMeta_UserStatus" json:"status,omitempty"`
	IsDelete             bool                                                                    `protobuf:"varint,9,opt,name=is_delete,json=isDelete,proto3" json:"isDelete,omitempty"`
	RoleId               string                                                                  `protobuf:"bytes,10,opt,name=role_id,json=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                `json:"-"`
	XXX_unrecognized     []byte                                                                  `json:"-"`
	XXX_sizecache        int32                                                                   `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{9}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CreateUserRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *CreateUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateUserRequest) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *CreateUserRequest) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{10}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SendActivationMailRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"userId" valid:"required,uuid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendActivationMailRequest) Reset()         { *m = SendActivationMailRequest{} }
func (m *SendActivationMailRequest) String() string { return proto.CompactTextString(m) }
func (*SendActivationMailRequest) ProtoMessage()    {}
func (*SendActivationMailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{11}
}
func (m *SendActivationMailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendActivationMailRequest.Unmarshal(m, b)
}
func (m *SendActivationMailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendActivationMailRequest.Marshal(b, m, deterministic)
}
func (m *SendActivationMailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendActivationMailRequest.Merge(m, src)
}
func (m *SendActivationMailRequest) XXX_Size() int {
	return xxx_messageInfo_SendActivationMailRequest.Size(m)
}
func (m *SendActivationMailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendActivationMailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendActivationMailRequest proto.InternalMessageInfo

func (m *SendActivationMailRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ActivateAccountRequest struct {
	Token                *github_com_MicroOps_cn_fuck_web_pkg_service_models.Secret `protobuf:"bytes,1,opt,name=token,proto3,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.Secret" json:"token,omitempty"`
	UserId               string                                                     `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"userId" valid:"required,uuid"`
	NewPassword          *github_com_MicroOps_cn_fuck_web_pkg_service_models.Secret `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.Secret" json:"newPassword" valid:"required"`
	XXX_NoUnkeyedLiteral struct{}                                                   `json:"-"`
	XXX_unrecognized     []byte                                                     `json:"-"`
	XXX_sizecache        int32                                                      `json:"-"`
}

func (m *ActivateAccountRequest) Reset()         { *m = ActivateAccountRequest{} }
func (m *ActivateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateAccountRequest) ProtoMessage()    {}
func (*ActivateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{12}
}
func (m *ActivateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateAccountRequest.Unmarshal(m, b)
}
func (m *ActivateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateAccountRequest.Marshal(b, m, deterministic)
}
func (m *ActivateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateAccountRequest.Merge(m, src)
}
func (m *ActivateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateAccountRequest.Size(m)
}
func (m *ActivateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateAccountRequest proto.InternalMessageInfo

func (m *ActivateAccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CreateTOTPSecretRequest struct {
	Token                *github_com_MicroOps_cn_fuck_web_pkg_service_models.Secret `protobuf:"bytes,1,opt,name=token,proto3,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.Secret" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                   `json:"-"`
	XXX_unrecognized     []byte                                                     `json:"-"`
	XXX_sizecache        int32                                                      `json:"-"`
}

func (m *CreateTOTPSecretRequest) Reset()         { *m = CreateTOTPSecretRequest{} }
func (m *CreateTOTPSecretRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTOTPSecretRequest) ProtoMessage()    {}
func (*CreateTOTPSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{13}
}
func (m *CreateTOTPSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTOTPSecretRequest.Unmarshal(m, b)
}
func (m *CreateTOTPSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTOTPSecretRequest.Marshal(b, m, deterministic)
}
func (m *CreateTOTPSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTOTPSecretRequest.Merge(m, src)
}
func (m *CreateTOTPSecretRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTOTPSecretRequest.Size(m)
}
func (m *CreateTOTPSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTOTPSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTOTPSecretRequest proto.InternalMessageInfo

type CreateTOTPSecretResponseData struct {
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTOTPSecretResponseData) Reset()         { *m = CreateTOTPSecretResponseData{} }
func (m *CreateTOTPSecretResponseData) String() string { return proto.CompactTextString(m) }
func (*CreateTOTPSecretResponseData) ProtoMessage()    {}
func (*CreateTOTPSecretResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{14}
}
func (m *CreateTOTPSecretResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTOTPSecretResponseData.Unmarshal(m, b)
}
func (m *CreateTOTPSecretResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTOTPSecretResponseData.Marshal(b, m, deterministic)
}
func (m *CreateTOTPSecretResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTOTPSecretResponseData.Merge(m, src)
}
func (m *CreateTOTPSecretResponseData) XXX_Size() int {
	return xxx_messageInfo_CreateTOTPSecretResponseData.Size(m)
}
func (m *CreateTOTPSecretResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTOTPSecretResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTOTPSecretResponseData proto.InternalMessageInfo

func (m *CreateTOTPSecretResponseData) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *CreateTOTPSecretResponseData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateTOTPSecretResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_list_response,json=baseListResponse,proto3,embedded=base_list_response" json:",omitempty"`
	Data                 *CreateTOTPSecretResponseData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CreateTOTPSecretResponse) Reset()         { *m = CreateTOTPSecretResponse{} }
func (m *CreateTOTPSecretResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTOTPSecretResponse) ProtoMessage()    {}
func (*CreateTOTPSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{15}
}
func (m *CreateTOTPSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTOTPSecretResponse.Unmarshal(m, b)
}
func (m *CreateTOTPSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTOTPSecretResponse.Marshal(b, m, deterministic)
}
func (m *CreateTOTPSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTOTPSecretResponse.Merge(m, src)
}
func (m *CreateTOTPSecretResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTOTPSecretResponse.Size(m)
}
func (m *CreateTOTPSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTOTPSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTOTPSecretResponse proto.InternalMessageInfo

func (m *CreateTOTPSecretResponse) GetData() *CreateTOTPSecretResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateTOTPRequest struct {
	Token                *github_com_MicroOps_cn_fuck_web_pkg_service_models.Secret `protobuf:"bytes,1,opt,name=token,proto3,customtype=github.com/MicroOps-cn/fuck-web/pkg/service/models.Secret" json:"token" valid:"required"`
	FirstCode            string                                                     `protobuf:"bytes,2,opt,name=first_code,json=firstCode,proto3" json:"firstCode" valid:"required"`
	SecondCode           string                                                     `protobuf:"bytes,3,opt,name=second_code,json=secondCode,proto3" json:"secondCode" valid:"required"`
	XXX_NoUnkeyedLiteral struct{}                                                   `json:"-"`
	XXX_unrecognized     []byte                                                     `json:"-"`
	XXX_sizecache        int32                                                      `json:"-"`
}

func (m *CreateTOTPRequest) Reset()         { *m = CreateTOTPRequest{} }
func (m *CreateTOTPRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTOTPRequest) ProtoMessage()    {}
func (*CreateTOTPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{16}
}
func (m *CreateTOTPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTOTPRequest.Unmarshal(m, b)
}
func (m *CreateTOTPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTOTPRequest.Marshal(b, m, deterministic)
}
func (m *CreateTOTPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTOTPRequest.Merge(m, src)
}
func (m *CreateTOTPRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTOTPRequest.Size(m)
}
func (m *CreateTOTPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTOTPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTOTPRequest proto.InternalMessageInfo

func (m *CreateTOTPRequest) GetFirstCode() string {
	if m != nil {
		return m.FirstCode
	}
	return ""
}

func (m *CreateTOTPRequest) GetSecondCode() string {
	if m != nil {
		return m.SecondCode
	}
	return ""
}

type PatchCurrentUserRequest struct {
	EmailAsMfa           *bool    `protobuf:"varint,1,opt,name=email_as_mfa,json=emailAsMfa,proto3,customtype=bool" json:"email_as_mfa,omitempty"`
	SmsAsMfa             *bool    `protobuf:"varint,2,opt,name=sms_as_mfa,json=smsAsMfa,proto3,customtype=bool" json:"sms_as_mfa,omitempty"`
	TotpAsMfa            *bool    `protobuf:"varint,3,opt,name=totp_as_mfa,json=totpAsMfa,proto3,customtype=bool" json:"totp_as_mfa,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchCurrentUserRequest) Reset()         { *m = PatchCurrentUserRequest{} }
func (m *PatchCurrentUserRequest) String() string { return proto.CompactTextString(m) }
func (*PatchCurrentUserRequest) ProtoMessage()    {}
func (*PatchCurrentUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{17}
}
func (m *PatchCurrentUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchCurrentUserRequest.Unmarshal(m, b)
}
func (m *PatchCurrentUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchCurrentUserRequest.Marshal(b, m, deterministic)
}
func (m *PatchCurrentUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchCurrentUserRequest.Merge(m, src)
}
func (m *PatchCurrentUserRequest) XXX_Size() int {
	return xxx_messageInfo_PatchCurrentUserRequest.Size(m)
}
func (m *PatchCurrentUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchCurrentUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchCurrentUserRequest proto.InternalMessageInfo

type PatchCurrentUserResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,embedded=base_response" json:",omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchCurrentUserResponse) Reset()         { *m = PatchCurrentUserResponse{} }
func (m *PatchCurrentUserResponse) String() string { return proto.CompactTextString(m) }
func (*PatchCurrentUserResponse) ProtoMessage()    {}
func (*PatchCurrentUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5931f5b5fc2d3f55, []int{18}
}
func (m *PatchCurrentUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchCurrentUserResponse.Unmarshal(m, b)
}
func (m *PatchCurrentUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchCurrentUserResponse.Marshal(b, m, deterministic)
}
func (m *PatchCurrentUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchCurrentUserResponse.Merge(m, src)
}
func (m *PatchCurrentUserResponse) XXX_Size() int {
	return xxx_messageInfo_PatchCurrentUserResponse.Size(m)
}
func (m *PatchCurrentUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchCurrentUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PatchCurrentUserResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UserInfo)(nil), "fuck_web.endpoint.UserInfo")
	proto.RegisterType((*GetUsersRequest)(nil), "fuck_web.endpoint.GetUsersRequest")
	proto.RegisterType((*GetUserResponse)(nil), "fuck_web.endpoint.GetUserResponse")
	proto.RegisterType((*GetUsersResponse)(nil), "fuck_web.endpoint.GetUsersResponse")
	proto.RegisterType((*PatchUserRequest)(nil), "fuck_web.endpoint.PatchUserRequest")
	proto.RegisterType((*ResetUserPasswordRequest)(nil), "fuck_web.endpoint.ResetUserPasswordRequest")
	proto.RegisterType((*ForgotUserPasswordRequest)(nil), "fuck_web.endpoint.ForgotUserPasswordRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "fuck_web.endpoint.DeleteUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "fuck_web.endpoint.UpdateUserRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "fuck_web.endpoint.CreateUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "fuck_web.endpoint.GetUserRequest")
	proto.RegisterType((*SendActivationMailRequest)(nil), "fuck_web.endpoint.SendActivationMailRequest")
	proto.RegisterType((*ActivateAccountRequest)(nil), "fuck_web.endpoint.ActivateAccountRequest")
	proto.RegisterType((*CreateTOTPSecretRequest)(nil), "fuck_web.endpoint.CreateTOTPSecretRequest")
	proto.RegisterType((*CreateTOTPSecretResponseData)(nil), "fuck_web.endpoint.CreateTOTPSecretResponseData")
	proto.RegisterType((*CreateTOTPSecretResponse)(nil), "fuck_web.endpoint.CreateTOTPSecretResponse")
	proto.RegisterType((*CreateTOTPRequest)(nil), "fuck_web.endpoint.CreateTOTPRequest")
	proto.RegisterType((*PatchCurrentUserRequest)(nil), "fuck_web.endpoint.PatchCurrentUserRequest")
	proto.RegisterType((*PatchCurrentUserResponse)(nil), "fuck_web.endpoint.PatchCurrentUserResponse")
}

func init() { proto.RegisterFile("endpoints/users.proto", fileDescriptor_5931f5b5fc2d3f55) }

var fileDescriptor_5931f5b5fc2d3f55 = []byte{
	// 1382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xcd, 0x6f, 0x13, 0x47,
	0x14, 0x67, 0x6d, 0xc7, 0xb1, 0x5f, 0x02, 0x24, 0x43, 0x08, 0x1b, 0xfa, 0xb1, 0xe9, 0x52, 0x55,
	0x81, 0x62, 0xbb, 0x22, 0x6a, 0x2b, 0xbe, 0xa4, 0xc6, 0xa1, 0x54, 0xa0, 0x06, 0xa2, 0x0d, 0xa0,
	0x96, 0x7e, 0x6c, 0xd7, 0xbb, 0xe3, 0xb0, 0x62, 0x77, 0xc7, 0xec, 0xcc, 0x26, 0x50, 0xa9, 0x27,
	0xae, 0x6d, 0xc5, 0xa1, 0x52, 0xaf, 0x3d, 0x72, 0xaa, 0xd4, 0x7f, 0xa2, 0xea, 0xa1, 0x87, 0x9e,
	0x73, 0xd8, 0x3f, 0xc0, 0x47, 0x8e, 0x3d, 0x55, 0x33, 0xb3, 0x6b, 0x4f, 0x1c, 0x27, 0x90, 0x84,
	0xd0, 0xf6, 0xe4, 0xcd, 0x6f, 0xde, 0xfc, 0xe6, 0xcd, 0x9b, 0x79, 0xef, 0xfd, 0x26, 0x70, 0x1c,
	0x47, 0x5e, 0x87, 0xf8, 0x11, 0xa3, 0x8d, 0x84, 0xe2, 0x98, 0xd6, 0x3b, 0x31, 0x61, 0x04, 0x4d,
	0xb6, 0x13, 0xf7, 0xbe, 0xbd, 0x8e, 0x5b, 0xf5, 0x7c, 0xfc, 0xe4, 0xd4, 0x2a, 0x59, 0x25, 0x62,
	0xb4, 0xc1, 0xbf, 0xa4, 0xe1, 0xc9, 0xa9, 0xfe, 0xfc, 0x96, 0x43, 0x71, 0x86, 0x1e, 0x0b, 0x89,
	0x87, 0x03, 0xda, 0x90, 0x3f, 0x12, 0x34, 0x7f, 0x1c, 0x85, 0xca, 0x6d, 0x8a, 0xe3, 0x6b, 0x51,
	0x9b, 0xa0, 0x06, 0x14, 0x7c, 0x4f, 0xd7, 0x66, 0xb5, 0xb9, 0x6a, 0xd3, 0xe8, 0xa6, 0x46, 0xc1,
	0xf7, 0x9e, 0xa5, 0xc6, 0xf1, 0x35, 0x27, 0xf0, 0xbd, 0x0b, 0x66, 0x8c, 0x1f, 0x24, 0x7e, 0x8c,
	0xbd, 0xb3, 0x49, 0xe2, 0x7b, 0xa6, 0x55, 0xf0, 0x3d, 0x74, 0x07, 0x2a, 0xdc, 0xc1, 0xc8, 0x09,
	0xb1, 0x5e, 0x10, 0xd3, 0x2e, 0x74, 0x53, 0xa3, 0x87, 0x3d, 0x4b, 0x8d, 0x33, 0x83, 0x93, 0x43,
	0x87, 0xb9, 0xf7, 0x30, 0x9d, 0xfb, 0xfa, 0x8b, 0x9a, 0xbd, 0x50, 0xbb, 0xeb, 0xd4, 0xbe, 0x7d,
	0xaf, 0x76, 0xfe, 0xab, 0x77, 0xdf, 0x3e, 0x6d, 0x5a, 0xbd, 0x79, 0xe8, 0x27, 0x0d, 0xca, 0x94,
	0x39, 0x2c, 0xa1, 0x7a, 0x71, 0x56, 0x9b, 0x3b, 0x72, 0xee, 0x6c, 0xbd, 0xb7, 0x77, 0x8a, 0xe3,
	0x35, 0xdf, 0xc5, 0xf5, 0x6c, 0x1b, 0xdc, 0xf9, 0x25, 0xcc, 0x1c, 0xf1, 0xb1, 0x22, 0xe6, 0x34,
	0x6f, 0xfc, 0x91, 0x1a, 0x87, 0x36, 0x52, 0xe3, 0xea, 0xaa, 0xcf, 0xee, 0x25, 0xad, 0xba, 0x4b,
	0xc2, 0xc6, 0x92, 0xef, 0xc6, 0xe4, 0x66, 0x87, 0xd6, 0xdc, 0xa8, 0xc1, 0xb9, 0x6a, 0xeb, 0xb8,
	0xd5, 0xe8, 0xdc, 0x5f, 0x6d, 0x64, 0x7c, 0x8d, 0x01, 0x3e, 0xbb, 0xcf, 0x67, 0x65, 0xbe, 0xa0,
	0x29, 0x18, 0xc1, 0xa1, 0xe3, 0x07, 0xfa, 0x08, 0xdf, 0xab, 0x25, 0xff, 0x40, 0xf3, 0x50, 0x6d,
	0x27, 0x41, 0x60, 0x8b, 0x28, 0x94, 0x45, 0x14, 0xa6, 0xbb, 0xa9, 0x81, 0x38, 0x78, 0xc3, 0x09,
	0xf1, 0x59, 0x12, 0xfa, 0x0c, 0x87, 0x1d, 0xf6, 0xc8, 0xaa, 0xe4, 0x18, 0x9a, 0x86, 0xb2, 0xb3,
	0xe6, 0x30, 0x27, 0xd6, 0x47, 0x05, 0x57, 0xf6, 0x17, 0xba, 0x04, 0xe3, 0x9d, 0x7b, 0x24, 0xc2,
	0x76, 0x94, 0x84, 0x2d, 0x1c, 0xeb, 0x15, 0xc1, 0x37, 0xd3, 0x4d, 0x8d, 0xe3, 0x02, 0xbf, 0x21,
	0x60, 0x85, 0x72, 0x4c, 0x81, 0x11, 0x82, 0x52, 0x4c, 0x02, 0xac, 0x57, 0x05, 0xa7, 0xf8, 0x46,
	0x35, 0x18, 0xe5, 0xbf, 0xb6, 0xef, 0xe9, 0x20, 0xc8, 0xa6, 0xba, 0xa9, 0x31, 0xc1, 0xa1, 0x6b,
	0x9e, 0xc2, 0x53, 0x96, 0x08, 0xfa, 0x00, 0x20, 0x20, 0xab, 0x7e, 0x64, 0x33, 0x3f, 0xc4, 0xfa,
	0x98, 0x98, 0x71, 0xa2, 0x9b, 0x1a, 0xc7, 0x04, 0x7a, 0xcb, 0xdf, 0xb4, 0x9f, 0x6a, 0x0f, 0x44,
	0x8b, 0x30, 0x96, 0x74, 0x3c, 0x87, 0x61, 0x39, 0x71, 0x5c, 0x4c, 0x34, 0xbb, 0xa9, 0x01, 0x12,
	0xe6, 0x46, 0xcf, 0x52, 0x63, 0x62, 0xe0, 0x3e, 0x98, 0x96, 0x32, 0xce, 0x49, 0xdc, 0x18, 0xf7,
	0x48, 0x0e, 0xf7, 0x49, 0x24, 0xbc, 0x3d, 0x49, 0x7f, 0x1c, 0x5d, 0x86, 0xaa, 0x4f, 0x6d, 0x0f,
	0x07, 0x98, 0x61, 0xfd, 0xc8, 0xac, 0x36, 0x57, 0x69, 0xce, 0xf2, 0x5b, 0xe9, 0xd3, 0x2b, 0x02,
	0x1b, 0x4a, 0xd0, 0x1b, 0x45, 0xdf, 0xc1, 0x61, 0xfc, 0x90, 0xe1, 0xc8, 0xc3, 0x9e, 0xed, 0x39,
	0xcc, 0xd1, 0x8f, 0x0a, 0x2f, 0x3e, 0xdb, 0x48, 0x8d, 0x0b, 0x7b, 0xbc, 0x4f, 0x1f, 0x3f, 0x64,
	0xdd, 0xd4, 0x98, 0xce, 0x69, 0xaf, 0x38, 0xcc, 0x51, 0x82, 0x38, 0xae, 0xe2, 0xe6, 0x93, 0x02,
	0x1c, 0xfd, 0x04, 0x33, 0x3e, 0x8d, 0x5a, 0xf8, 0x41, 0x82, 0x29, 0x43, 0x6d, 0x98, 0xe4, 0x79,
	0x6c, 0x07, 0x3e, 0x65, 0x76, 0x2c, 0x41, 0x91, 0xa6, 0x63, 0xe7, 0xcc, 0xfa, 0x96, 0xa2, 0x50,
	0x6f, 0x3a, 0x14, 0x7f, 0xea, 0x53, 0x96, 0x4d, 0x6f, 0x4e, 0xf3, 0x74, 0xf8, 0x2b, 0x35, 0x34,
	0x1e, 0x48, 0x65, 0xe1, 0xa3, 0xad, 0xcd, 0x86, 0x6a, 0xda, 0x95, 0xf6, 0x98, 0x76, 0xda, 0xcb,
	0x4f, 0x3b, 0xf3, 0x17, 0xad, 0x17, 0x12, 0x0b, 0xd3, 0x0e, 0x89, 0x28, 0x46, 0x5f, 0xc2, 0x61,
	0x11, 0x92, 0x38, 0x03, 0xb2, 0x70, 0x18, 0xdb, 0x84, 0x23, 0x9f, 0xb7, 0x6d, 0x2c, 0xc6, 0x5b,
	0x8a, 0x15, 0x6a, 0x40, 0x49, 0x1c, 0x7d, 0x41, 0x90, 0xbe, 0x36, 0x84, 0x34, 0xaf, 0x99, 0x96,
	0x30, 0x34, 0x7f, 0xd5, 0x60, 0xa2, 0x7f, 0x6a, 0x19, 0x8b, 0x0f, 0x48, 0x3d, 0xb6, 0x4d, 0x8e,
	0x9e, 0xda, 0xf1, 0xdc, 0x9e, 0xe3, 0xec, 0x44, 0x6b, 0xc0, 0x52, 0x71, 0xb8, 0xf8, 0x62, 0x0e,
	0xff, 0x50, 0x80, 0x89, 0x65, 0x5e, 0x8a, 0x65, 0x54, 0xe5, 0xf9, 0x9f, 0x56, 0xea, 0xff, 0xcc,
	0xce, 0x95, 0xff, 0x49, 0xff, 0xaa, 0x14, 0xf6, 0x70, 0x55, 0xae, 0x1f, 0x40, 0x75, 0xbe, 0xa8,
	0xe6, 0x7d, 0x51, 0xe4, 0xfd, 0x9b, 0x1b, 0xa9, 0x51, 0x6a, 0x11, 0x12, 0xf0, 0x7a, 0x9c, 0x67,
	0xb8, 0x5a, 0x8f, 0x73, 0xcc, 0xfc, 0xbb, 0x08, 0xba, 0x85, 0xa9, 0x3c, 0xc2, 0x65, 0x87, 0xd2,
	0x75, 0x12, 0x7b, 0x79, 0x5c, 0x56, 0x60, 0x84, 0x91, 0xfb, 0x38, 0xca, 0x42, 0x73, 0x79, 0x23,
	0x35, 0xce, 0xef, 0xc1, 0xf9, 0x15, 0xec, 0xc6, 0x98, 0x59, 0x92, 0x0b, 0x3d, 0x82, 0x71, 0x12,
	0x78, 0x76, 0x27, 0x5b, 0x2b, 0xeb, 0x9f, 0x77, 0xf6, 0xc5, 0xcd, 0xdb, 0x04, 0x09, 0xbc, 0xdc,
	0x7f, 0xb5, 0x4d, 0x28, 0x30, 0xba, 0x04, 0xa3, 0xbc, 0xd5, 0xf2, 0x96, 0x50, 0x14, 0xab, 0x9e,
	0xea, 0xa6, 0x46, 0x99, 0x43, 0xd7, 0xd4, 0x86, 0x4f, 0x3a, 0xcc, 0x27, 0x91, 0x13, 0x64, 0xc7,
	0x9e, 0x19, 0xa0, 0xc7, 0x1a, 0x8c, 0x47, 0x78, 0xbd, 0xef, 0xb9, 0xe8, 0x86, 0xcd, 0x6f, 0xf6,
	0xeb, 0xf9, 0x58, 0x84, 0xd7, 0x73, 0x17, 0x87, 0xd6, 0x68, 0xd5, 0x00, 0x5d, 0x57, 0xa4, 0x87,
	0x6c, 0xba, 0x75, 0x45, 0x6e, 0xf4, 0x5c, 0x7f, 0x11, 0xb9, 0x61, 0x3e, 0xd5, 0x60, 0xe6, 0x2a,
	0x89, 0x57, 0xc9, 0xd0, 0xd3, 0x57, 0x45, 0x8e, 0xf6, 0x12, 0x45, 0xce, 0x7c, 0xae, 0x26, 0xe4,
	0xc9, 0xbf, 0xd1, 0x4d, 0x0d, 0x09, 0x0c, 0xdd, 0xbc, 0x1c, 0x32, 0xaf, 0xc0, 0xa4, 0xbc, 0xb1,
	0x6a, 0xde, 0xee, 0x56, 0xb7, 0x99, 0x7f, 0x96, 0x60, 0xf2, 0xb6, 0x68, 0xbb, 0xfb, 0xa1, 0x39,
	0x30, 0xf9, 0xf7, 0x74, 0x7f, 0xf2, 0xaf, 0xf5, 0x72, 0xe5, 0x1f, 0x97, 0x4b, 0xd2, 0x1b, 0x55,
	0x2e, 0xfd, 0x5f, 0x24, 0xe1, 0xbc, 0x5a, 0x15, 0xab, 0xa2, 0x2a, 0x4e, 0x3f, 0xaf, 0x1a, 0xee,
	0x52, 0x33, 0x9a, 0x8f, 0x4b, 0x30, 0xb9, 0x28, 0x04, 0x98, 0x7a, 0x9d, 0x0e, 0x2a, 0x6f, 0x7a,
	0x21, 0x2f, 0x6e, 0x1b, 0xf2, 0xd2, 0xae, 0x43, 0x3e, 0xb2, 0x63, 0xc8, 0xcb, 0xbb, 0x0a, 0xb9,
	0xd2, 0x1b, 0x47, 0xff, 0x23, 0xbd, 0xf1, 0x55, 0xdc, 0x82, 0x05, 0x38, 0xd2, 0x53, 0x69, 0x7b,
	0xac, 0x4b, 0x9f, 0xc3, 0xcc, 0x0a, 0x8e, 0xbc, 0x05, 0x97, 0xf9, 0x6b, 0x0e, 0xaf, 0xe0, 0x4b,
	0x8e, 0x1f, 0xe4, 0x6c, 0x4a, 0xd7, 0xd2, 0x76, 0xe8, 0x5a, 0x03, 0xb4, 0x99, 0x81, 0xf9, 0x5b,
	0x01, 0xa6, 0x33, 0x5e, 0xbc, 0xe0, 0xba, 0x24, 0x89, 0xd8, 0x81, 0xb6, 0x77, 0xc5, 0xdb, 0xc2,
	0xae, 0xbd, 0xdd, 0xda, 0x63, 0x4b, 0xff, 0x42, 0x8f, 0x35, 0x23, 0x38, 0x21, 0xd3, 0xfa, 0xd6,
	0xcd, 0x5b, 0xcb, 0xd9, 0xf6, 0x0e, 0x30, 0x66, 0xa6, 0x0b, 0xaf, 0x6f, 0x5d, 0x4f, 0x2a, 0x5c,
	0xfe, 0x36, 0x42, 0x26, 0x94, 0xa9, 0x40, 0xb3, 0x90, 0x02, 0x0f, 0xa9, 0x44, 0xac, 0xec, 0x17,
	0x19, 0xb9, 0x63, 0x52, 0xd9, 0x54, 0x79, 0x57, 0x15, 0x40, 0xbe, 0xc8, 0xef, 0x1a, 0xe8, 0xdb,
	0xad, 0x82, 0xf0, 0x0e, 0x92, 0x7d, 0xcf, 0x6f, 0x8b, 0xad, 0x72, 0x7d, 0x71, 0xd3, 0xfb, 0xa2,
	0x31, 0x84, 0x78, 0xa7, 0x38, 0x64, 0x12, 0xfe, 0xfb, 0x42, 0x5e, 0x75, 0xb9, 0x59, 0x7e, 0x30,
	0x9d, 0xcd, 0x07, 0x73, 0x77, 0xbf, 0x37, 0x46, 0xb2, 0x0d, 0x97, 0x24, 0xf2, 0xa6, 0x7f, 0x04,
	0xd0, 0xf6, 0x63, 0xca, 0x6c, 0x97, 0x78, 0xb9, 0x0e, 0x78, 0xab, 0x9b, 0x1a, 0x55, 0x81, 0x2e,
	0x12, 0x6f, 0xf8, 0x8b, 0xbb, 0x3f, 0xcc, 0x9f, 0xfd, 0x14, 0xbb, 0x24, 0xf2, 0x24, 0x45, 0xb1,
	0xff, 0xec, 0x97, 0xf0, 0xb6, 0x1c, 0xca, 0xb8, 0xf9, 0xb3, 0x06, 0x27, 0xc4, 0x8b, 0x66, 0x31,
	0x89, 0x63, 0x1c, 0x6d, 0x2a, 0x44, 0x67, 0x60, 0x5c, 0x74, 0x09, 0xdb, 0xa1, 0x76, 0xd8, 0x76,
	0x44, 0x6c, 0x2a, 0xcd, 0x4a, 0xfe, 0x3a, 0xb0, 0x40, 0x8c, 0x2e, 0xd0, 0xa5, 0xb6, 0x83, 0xde,
	0x01, 0xa0, 0x21, 0xcd, 0x2d, 0x0b, 0x03, 0x96, 0x15, 0x1a, 0x52, 0x69, 0x37, 0x07, 0x63, 0x8c,
	0xb0, 0x4e, 0x6e, 0x58, 0x1c, 0x30, 0xac, 0xf2, 0x41, 0x61, 0x69, 0x3e, 0x04, 0x7d, 0xab, 0x63,
	0xaf, 0xe2, 0x1d, 0xdb, 0xfc, 0xf0, 0xee, 0xfb, 0x2f, 0x72, 0xf6, 0xf9, 0x12, 0x17, 0xf3, 0x8f,
	0xe5, 0x43, 0xad, 0xb2, 0xf8, 0xff, 0xe0, 0xfc, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x60,
	0x44, 0x34, 0x8c, 0x14, 0x00, 0x00,
}
