// Code generated by fuck-web. DO NOT EDIT.

export enum PasswordComplexity{
  unsafe = 0,
  general = 1,
  safe = 2,
  very_safe = 3,
}

export type PasswordComplexityName =
    | 'unsafe'
    | 'general'
    | 'safe'
    | 'very_safe';

export type PasswordComplexityValue =
    | 0
    | 1
    | 2
    | 3;

export enum LoginType{
  mfa_email = 2,
  email = 4,
  enable_mfa_sms = 12,
  enable_mfa_totp = 10,
  enable_mfa_email = 11,
  normal = 0,
  mfa_totp = 1,
  mfa_sms = 3,
  sms = 5,
  oauth2 = 6,
}

export type LoginTypeName =
    | 'enable_mfa_totp'
    | 'enable_mfa_email'
    | 'normal'
    | 'mfa_totp'
    | 'mfa_sms'
    | 'sms'
    | 'oauth2'
    | 'mfa_email'
    | 'email'
    | 'enable_mfa_sms';

export type LoginTypeValue =
    | 1
    | 3
    | 5
    | 6
    | 10
    | 11
    | 0
    | 4
    | 12
    | 2;

export enum AuthMethod{
  token = 2,
  token_signature = 3,
  basic = 0,
  signature = 1,
}

export type AuthMethodName =
    | 'basic'
    | 'signature'
    | 'token'
    | 'token_signature';

export type AuthMethodValue =
    | 0
    | 1
    | 2
    | 3;

export enum RoleType{
  user = 0,
  system = 1,
}

export type RoleTypeName =
    | 'user'
    | 'system';

export type RoleTypeValue =
    | 0
    | 1;

export enum UserStatus{
  disabled = 1,
  user_inactive = 2,
  password_expired = 4,
  normal = 0,
}

export type UserStatusName =
    | 'normal'
    | 'disabled'
    | 'user_inactive'
    | 'password_expired';

export type UserStatusValue =
    | 0
    | 1
    | 2
    | 4;

