// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/geoip.proto

package geoip

import (
	fmt "fmt"
	github_com_MicroOps_cn_fuck_sets "github.com/MicroOps-cn/fuck/sets"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Duration from public import google/protobuf/duration.proto
type Duration = types.Duration

type CustomGeoOptions struct {
	Name                 string                                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subnets              github_com_MicroOps_cn_fuck_sets.IPNets `protobuf:"bytes,2,opt,name=subnets,proto3,customtype=github.com/MicroOps-cn/fuck/sets.IPNets" json:"subnets"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *CustomGeoOptions) Reset()         { *m = CustomGeoOptions{} }
func (m *CustomGeoOptions) String() string { return proto.CompactTextString(m) }
func (*CustomGeoOptions) ProtoMessage()    {}
func (*CustomGeoOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_02369b33dee0b6ba, []int{0}
}
func (m *CustomGeoOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomGeoOptions.Unmarshal(m, b)
}
func (m *CustomGeoOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomGeoOptions.Marshal(b, m, deterministic)
}
func (m *CustomGeoOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomGeoOptions.Merge(m, src)
}
func (m *CustomGeoOptions) XXX_Size() int {
	return xxx_messageInfo_CustomGeoOptions.Size(m)
}
func (m *CustomGeoOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomGeoOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CustomGeoOptions proto.InternalMessageInfo

func (m *CustomGeoOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GeoIPOptions struct {
	Path                 string              `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Custom               []*CustomGeoOptions `protobuf:"bytes,2,rep,name=custom,proto3" json:"custom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GeoIPOptions) Reset()         { *m = GeoIPOptions{} }
func (m *GeoIPOptions) String() string { return proto.CompactTextString(m) }
func (*GeoIPOptions) ProtoMessage()    {}
func (*GeoIPOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_02369b33dee0b6ba, []int{1}
}
func (m *GeoIPOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoIPOptions.Unmarshal(m, b)
}
func (m *GeoIPOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoIPOptions.Marshal(b, m, deterministic)
}
func (m *GeoIPOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoIPOptions.Merge(m, src)
}
func (m *GeoIPOptions) XXX_Size() int {
	return xxx_messageInfo_GeoIPOptions.Size(m)
}
func (m *GeoIPOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoIPOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GeoIPOptions proto.InternalMessageInfo

func (m *GeoIPOptions) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GeoIPOptions) GetCustom() []*CustomGeoOptions {
	if m != nil {
		return m.Custom
	}
	return nil
}

func init() {
	proto.RegisterType((*CustomGeoOptions)(nil), "fuck_web.client.geoip.CustomGeoOptions")
	proto.RegisterType((*GeoIPOptions)(nil), "fuck_web.client.geoip.GeoIPOptions")
}

func init() { proto.RegisterFile("types/geoip.proto", fileDescriptor_02369b33dee0b6ba) }

var fileDescriptor_02369b33dee0b6ba = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x4f, 0x4f, 0xcd, 0xcf, 0x2c, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4d,
	0x2b, 0x4d, 0xce, 0x8e, 0x2f, 0x4f, 0x4d, 0xd2, 0x4b, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x03,
	0x4b, 0x4a, 0x89, 0xa4, 0xe7, 0xa7, 0xe7, 0x83, 0x55, 0xe8, 0x83, 0x58, 0x10, 0xc5, 0x52, 0x72,
	0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x5e, 0x52, 0x69, 0x9a, 0x7e, 0x4a, 0x69, 0x51,
	0x62, 0x49, 0x66, 0x7e, 0x1e, 0x44, 0x5e, 0xa9, 0x90, 0x4b, 0xc0, 0xb9, 0xb4, 0xb8, 0x24, 0x3f,
	0xd7, 0x3d, 0x35, 0xdf, 0xbf, 0x00, 0x24, 0x51, 0x2c, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b,
	0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x79, 0x72, 0xb1, 0x17, 0x97, 0x26,
	0xe5, 0xa5, 0x96, 0x14, 0x4b, 0x30, 0x81, 0x84, 0x9d, 0xf4, 0x4f, 0xdc, 0x93, 0x67, 0xb8, 0x75,
	0x4f, 0x5e, 0x3d, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0xdf, 0x37, 0x33,
	0xb9, 0x28, 0xdf, 0xbf, 0xa0, 0x58, 0x37, 0x39, 0x4f, 0x1f, 0xe4, 0x48, 0xfd, 0xe2, 0xd4, 0x92,
	0x62, 0x3d, 0xcf, 0x00, 0xbf, 0xd4, 0x92, 0xe2, 0x20, 0x98, 0x7e, 0xa5, 0x64, 0x2e, 0x1e, 0xf7,
	0xd4, 0x7c, 0xcf, 0x00, 0x24, 0xeb, 0x0a, 0x12, 0x4b, 0x32, 0x60, 0xd6, 0x81, 0xd8, 0x42, 0xf6,
	0x5c, 0x6c, 0xc9, 0x60, 0x67, 0x49, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x1b, 0xa9, 0xeb, 0x61, 0xf5,
	0xb4, 0x1e, 0xba, 0xdb, 0x83, 0xa0, 0xda, 0x9c, 0x2c, 0xa2, 0xcc, 0xf0, 0x38, 0x4c, 0xb7, 0x3c,
	0x35, 0x49, 0xbf, 0x20, 0x3b, 0x5d, 0x1f, 0x62, 0x18, 0x24, 0x78, 0xad, 0xc1, 0x64, 0x00, 0x43,
	0x00, 0x63, 0x12, 0x1b, 0x38, 0x70, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x1b, 0xe2,
	0x5a, 0x7e, 0x01, 0x00, 0x00,
}
