// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/email.proto

package email

import (
	fmt "fmt"
	github_com_MicroOps_cn_fuck_safe "github.com/MicroOps-cn/fuck/safe"
	proto "github.com/gogo/protobuf/proto"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OriginalTemplate struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	TemplateFile         string   `protobuf:"bytes,2,opt,name=template_file,json=templateFile,proto3" json:"template_file,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Set                  string   `protobuf:"bytes,4,opt,name=set,proto3" json:"set,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginalTemplate) Reset()         { *m = OriginalTemplate{} }
func (m *OriginalTemplate) String() string { return proto.CompactTextString(m) }
func (*OriginalTemplate) ProtoMessage()    {}
func (*OriginalTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_48615ec03fb78475, []int{0}
}
func (m *OriginalTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginalTemplate.Unmarshal(m, b)
}
func (m *OriginalTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginalTemplate.Marshal(b, m, deterministic)
}
func (m *OriginalTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginalTemplate.Merge(m, src)
}
func (m *OriginalTemplate) XXX_Size() int {
	return xxx_messageInfo_OriginalTemplate.Size(m)
}
func (m *OriginalTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginalTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_OriginalTemplate proto.InternalMessageInfo

func (m *OriginalTemplate) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *OriginalTemplate) GetTemplateFile() string {
	if m != nil {
		return m.TemplateFile
	}
	return ""
}

func (m *OriginalTemplate) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *OriginalTemplate) GetSet() string {
	if m != nil {
		return m.Set
	}
	return ""
}

type CustomType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomType) Reset()         { *m = CustomType{} }
func (m *CustomType) String() string { return proto.CompactTextString(m) }
func (*CustomType) ProtoMessage()    {}
func (*CustomType) Descriptor() ([]byte, []int) {
	return fileDescriptor_48615ec03fb78475, []int{1}
}
func (m *CustomType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomType.Unmarshal(m, b)
}
func (m *CustomType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomType.Marshal(b, m, deterministic)
}
func (m *CustomType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomType.Merge(m, src)
}
func (m *CustomType) XXX_Size() int {
	return xxx_messageInfo_CustomType.Size(m)
}
func (m *CustomType) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomType.DiscardUnknown(m)
}

var xxx_messageInfo_CustomType proto.InternalMessageInfo

type SmtpOptions struct {
	Username             string                                   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             *github_com_MicroOps_cn_fuck_safe.String `protobuf:"bytes,2,opt,name=password,proto3,customtype=github.com/MicroOps-cn/fuck/safe.String" json:"password,omitempty"`
	Host                 string                                   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32                                    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	From                 string                                   `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To                   []string                                 `protobuf:"bytes,6,rep,name=to,proto3" json:"to,omitempty"`
	Template             []Template                               `protobuf:"bytes,7,rep,name=template,proto3,customtype=Template" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *SmtpOptions) Reset()         { *m = SmtpOptions{} }
func (m *SmtpOptions) String() string { return proto.CompactTextString(m) }
func (*SmtpOptions) ProtoMessage()    {}
func (*SmtpOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_48615ec03fb78475, []int{2}
}
func (m *SmtpOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmtpOptions.Unmarshal(m, b)
}
func (m *SmtpOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmtpOptions.Marshal(b, m, deterministic)
}
func (m *SmtpOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmtpOptions.Merge(m, src)
}
func (m *SmtpOptions) XXX_Size() int {
	return xxx_messageInfo_SmtpOptions.Size(m)
}
func (m *SmtpOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SmtpOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SmtpOptions proto.InternalMessageInfo

func (m *SmtpOptions) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SmtpOptions) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *SmtpOptions) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SmtpOptions) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SmtpOptions) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func init() {
	proto.RegisterType((*OriginalTemplate)(nil), "fuck_web.client.email.OriginalTemplate")
	proto.RegisterType((*CustomType)(nil), "fuck_web.client.email.custom_type")
	proto.RegisterType((*SmtpOptions)(nil), "fuck_web.client.email.SmtpOptions")
}

func init() { proto.RegisterFile("types/email.proto", fileDescriptor_48615ec03fb78475) }

var fileDescriptor_48615ec03fb78475 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x25, 0xc9, 0x76, 0x37, 0xeb, 0xec, 0xa2, 0xc5, 0x5a, 0x24, 0x6b, 0x0f, 0xb4, 0x0a, 0x87,
	0xed, 0xa5, 0xb1, 0x54, 0x24, 0x2e, 0x70, 0xea, 0x81, 0x1b, 0x2a, 0xa4, 0x9c, 0xb8, 0x54, 0x89,
	0x71, 0x52, 0xd3, 0x24, 0x63, 0xd9, 0x13, 0x55, 0xfd, 0x34, 0xfe, 0x80, 0x6f, 0xe8, 0xa1, 0x42,
	0x7c, 0x09, 0x8a, 0xd3, 0x54, 0x08, 0x01, 0x97, 0xe8, 0xbd, 0x37, 0x4f, 0x33, 0xf3, 0xe2, 0x21,
	0xcf, 0x70, 0xaf, 0xa5, 0xe5, 0xb2, 0xce, 0x54, 0x95, 0x68, 0x03, 0x08, 0xf4, 0x79, 0xd1, 0x8a,
	0xed, 0x7a, 0x27, 0xf3, 0x44, 0x54, 0x4a, 0x36, 0x98, 0xb8, 0xe2, 0xc3, 0x7d, 0x09, 0x25, 0x38,
	0x07, 0xef, 0x50, 0x6f, 0x8e, 0xf7, 0xe4, 0x6e, 0x69, 0x54, 0xa9, 0x9a, 0xac, 0xfa, 0x24, 0x6b,
	0x5d, 0x65, 0x28, 0x29, 0x23, 0x57, 0xb6, 0xcd, 0xbf, 0x4a, 0x81, 0xcc, 0x9b, 0x78, 0xd3, 0xeb,
	0x74, 0xa0, 0xf4, 0x25, 0xb9, 0xc5, 0x93, 0x6b, 0x5d, 0xa8, 0x4a, 0x32, 0xdf, 0xd5, 0x6f, 0x06,
	0xf1, 0x9d, 0xaa, 0x24, 0xbd, 0x27, 0x23, 0x04, 0xad, 0x04, 0x0b, 0x5c, 0xb1, 0x27, 0xf4, 0x8e,
	0x04, 0x56, 0x22, 0xbb, 0x70, 0x5a, 0x07, 0xe3, 0x5b, 0x12, 0x89, 0xd6, 0x22, 0xd4, 0xeb, 0x2e,
	0x43, 0xfc, 0xcd, 0x27, 0xd1, 0xaa, 0x46, 0xbd, 0xd4, 0xa8, 0xa0, 0xb1, 0xf4, 0x81, 0x84, 0xad,
	0x95, 0xa6, 0xc9, 0x6a, 0x79, 0x5a, 0xe3, 0xcc, 0x29, 0x90, 0x50, 0x67, 0xd6, 0xee, 0xc0, 0x7c,
	0x71, 0x2b, 0x44, 0xf3, 0x38, 0xf9, 0x6b, 0xea, 0xe4, 0xb7, 0x09, 0x0b, 0xfe, 0xfd, 0x38, 0xf6,
	0x0e, 0xc7, 0xf1, 0x63, 0xa9, 0x70, 0xd3, 0xe6, 0x89, 0x80, 0x9a, 0xbf, 0x57, 0xc2, 0xc0, 0x52,
	0xdb, 0x99, 0x68, 0x78, 0xd7, 0x81, 0xdb, 0xac, 0x90, 0xc9, 0x0a, 0x8d, 0x6a, 0xca, 0xf4, 0x3c,
	0x84, 0x52, 0x72, 0xb1, 0x01, 0x8b, 0xa7, 0x48, 0x0e, 0x77, 0x9a, 0x06, 0xd3, 0x47, 0x1a, 0xa5,
	0x0e, 0x77, 0x5a, 0x61, 0xa0, 0x66, 0xa3, 0xde, 0xd7, 0x61, 0xfa, 0x94, 0xf8, 0x08, 0xec, 0x72,
	0x12, 0x4c, 0xaf, 0x53, 0x1f, 0x81, 0x7e, 0x24, 0xe1, 0xf0, 0xbf, 0xd8, 0xd5, 0x24, 0x98, 0x46,
	0xf3, 0xc7, 0x7f, 0x2c, 0xff, 0xe7, 0xcb, 0x2c, 0x6e, 0x0e, 0xc7, 0x71, 0x38, 0xb0, 0xf4, 0xdc,
	0x66, 0xf1, 0xf6, 0xc7, 0xcf, 0x17, 0xde, 0xe7, 0xd7, 0xff, 0xc9, 0x35, 0xdb, 0xc9, 0x9c, 0xeb,
	0x6d, 0xc9, 0xfb, 0x01, 0xfd, 0xc1, 0xbc, 0x71, 0xdf, 0x0f, 0x4f, 0xf2, 0x4b, 0x77, 0x0c, 0xaf,
	0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x83, 0x13, 0x8a, 0xbe, 0x4e, 0x02, 0x00, 0x00,
}

func (m *OriginalTemplate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovEmail(uint64(l))
	}
	l = len(m.TemplateFile)
	if l > 0 {
		n += 1 + l + sovEmail(uint64(l))
	}
	l = len(m.Topic)
	if l > 0 {
		n += 1 + l + sovEmail(uint64(l))
	}
	l = len(m.Set)
	if l > 0 {
		n += 1 + l + sovEmail(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CustomType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SmtpOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovEmail(uint64(l))
	}
	if m.Password != nil {
		l = m.Password.Size()
		n += 1 + l + sovEmail(uint64(l))
	}
	l = len(m.Host)
	if l > 0 {
		n += 1 + l + sovEmail(uint64(l))
	}
	if m.Port != 0 {
		n += 1 + sovEmail(uint64(m.Port))
	}
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovEmail(uint64(l))
	}
	if len(m.To) > 0 {
		for _, s := range m.To {
			l = len(s)
			n += 1 + l + sovEmail(uint64(l))
		}
	}
	if len(m.Template) > 0 {
		for _, e := range m.Template {
			l = e.Size()
			n += 1 + l + sovEmail(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovEmail(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEmail(x uint64) (n int) {
	return sovEmail(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
