// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: models/models.proto

package models

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	gorm_io_gorm "gorm.io/gorm"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// @sync-to-public:public/src/services/fuck-web/enums.ts:AuthMethod
type AuthMeta_Method int32

const (
	AuthMeta_basic           AuthMeta_Method = 0
	AuthMeta_signature       AuthMeta_Method = 1
	AuthMeta_token           AuthMeta_Method = 2
	AuthMeta_token_signature AuthMeta_Method = 3
)

var AuthMeta_Method_name = map[int32]string{
	0: "basic",
	1: "signature",
	2: "token",
	3: "token_signature",
}

var AuthMeta_Method_value = map[string]int32{
	"basic":           0,
	"signature":       1,
	"token":           2,
	"token_signature": 3,
}

func (x AuthMeta_Method) String() string {
	return proto.EnumName(AuthMeta_Method_name, int32(x))
}

func (AuthMeta_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{0, 0}
}

// @sync-to-public:public/src/services/fuck-web/enums.ts:RoleType
type RoleMeta_Type int32

const (
	RoleMeta_user   RoleMeta_Type = 0
	RoleMeta_system RoleMeta_Type = 1
)

var RoleMeta_Type_name = map[int32]string{
	0: "user",
	1: "system",
}

var RoleMeta_Type_value = map[string]int32{
	"user":   0,
	"system": 1,
}

func (x RoleMeta_Type) String() string {
	return proto.EnumName(RoleMeta_Type_name, int32(x))
}

func (RoleMeta_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{1, 0}
}

// @sync-to-public:public/src/services/fuck-web/enums.ts:UserStatus
type UserMeta_UserStatus int32

const (
	UserMeta_normal           UserMeta_UserStatus = 0
	UserMeta_disabled         UserMeta_UserStatus = 1
	UserMeta_user_inactive    UserMeta_UserStatus = 2
	UserMeta_password_expired UserMeta_UserStatus = 4
)

var UserMeta_UserStatus_name = map[int32]string{
	0: "normal",
	1: "disabled",
	2: "user_inactive",
	4: "password_expired",
}

var UserMeta_UserStatus_value = map[string]int32{
	"normal":           0,
	"disabled":         1,
	"user_inactive":    2,
	"password_expired": 4,
}

func (x UserMeta_UserStatus) String() string {
	return proto.EnumName(UserMeta_UserStatus_name, int32(x))
}

func (UserMeta_UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{2, 0}
}

type AuthMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthMeta) Reset()         { *m = AuthMeta{} }
func (m *AuthMeta) String() string { return proto.CompactTextString(m) }
func (*AuthMeta) ProtoMessage()    {}
func (*AuthMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{0}
}
func (m *AuthMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMeta.Unmarshal(m, b)
}
func (m *AuthMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMeta.Marshal(b, m, deterministic)
}
func (m *AuthMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMeta.Merge(m, src)
}
func (m *AuthMeta) XXX_Size() int {
	return xxx_messageInfo_AuthMeta.Size(m)
}
func (m *AuthMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMeta proto.InternalMessageInfo

type RoleMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleMeta) Reset()         { *m = RoleMeta{} }
func (m *RoleMeta) String() string { return proto.CompactTextString(m) }
func (*RoleMeta) ProtoMessage()    {}
func (*RoleMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{1}
}
func (m *RoleMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleMeta.Unmarshal(m, b)
}
func (m *RoleMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleMeta.Marshal(b, m, deterministic)
}
func (m *RoleMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleMeta.Merge(m, src)
}
func (m *RoleMeta) XXX_Size() int {
	return xxx_messageInfo_RoleMeta.Size(m)
}
func (m *RoleMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RoleMeta proto.InternalMessageInfo

type UserMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMeta) Reset()         { *m = UserMeta{} }
func (m *UserMeta) String() string { return proto.CompactTextString(m) }
func (*UserMeta) ProtoMessage()    {}
func (*UserMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{2}
}
func (m *UserMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMeta.Unmarshal(m, b)
}
func (m *UserMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMeta.Marshal(b, m, deterministic)
}
func (m *UserMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMeta.Merge(m, src)
}
func (m *UserMeta) XXX_Size() int {
	return xxx_messageInfo_UserMeta.Size(m)
}
func (m *UserMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMeta.DiscardUnknown(m)
}

var xxx_messageInfo_UserMeta proto.InternalMessageInfo

type Model struct {
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required" gorm:"primary_key;type:char(36)"`
	CreateTime time.Time              `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3,customtype=time.Time" json:"createTime,omitempty" gorm:"type:datetime;not null;omitempty"`
	UpdateTime time.Time              `protobuf:"bytes,3,opt,name=update_time,json=updateTime,proto3,customtype=time.Time" json:"updateTime,omitempty" gorm:"type:datetime;not null;omitempty"`
	IsDelete   bool                   `protobuf:"varint,4,opt,name=is_delete,json=isDelete,proto3" json:"isDelete,omitempty" gorm:"-"`
	DeleteTime gorm_io_gorm.DeletedAt `protobuf:"bytes,5,opt,name=delete_time,json=deleteTime,proto3,customtype=gorm.io/gorm.DeletedAt" json:"-" gorm:"type:datetime;omitempty"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{3}
}
func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Model) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func init() {
	proto.RegisterEnum("fuck_web.service.models.AuthMeta_Method", AuthMeta_Method_name, AuthMeta_Method_value)
	proto.RegisterEnum("fuck_web.service.models.RoleMeta_Type", RoleMeta_Type_name, RoleMeta_Type_value)
	proto.RegisterEnum("fuck_web.service.models.UserMeta_UserStatus", UserMeta_UserStatus_name, UserMeta_UserStatus_value)
	proto.RegisterType((*AuthMeta)(nil), "fuck_web.service.models.AuthMeta")
	proto.RegisterType((*RoleMeta)(nil), "fuck_web.service.models.RoleMeta")
	proto.RegisterType((*UserMeta)(nil), "fuck_web.service.models.UserMeta")
	proto.RegisterType((*Model)(nil), "fuck_web.service.models.Model")
}

func init() { proto.RegisterFile("models/models.proto", fileDescriptor_bb289c42926c4029) }

var fileDescriptor_bb289c42926c4029 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4f, 0x6f, 0xd3, 0x3c,
	0x18, 0x4f, 0xba, 0x6e, 0x4a, 0xbd, 0x4d, 0x6f, 0x5e, 0x6f, 0x82, 0x09, 0x21, 0x5c, 0xf9, 0x42,
	0x91, 0x68, 0x2a, 0x34, 0x09, 0x89, 0xf6, 0x80, 0x56, 0xc1, 0x09, 0x95, 0xa1, 0x32, 0x2e, 0x70,
	0x88, 0xdc, 0xf8, 0x59, 0x6a, 0x35, 0x89, 0x83, 0xed, 0x6c, 0xe4, 0x5b, 0x70, 0xe4, 0xca, 0x3e,
	0x0d, 0x47, 0xce, 0x1c, 0xf2, 0x01, 0x7a, 0xdc, 0x8d, 0x1b, 0x72, 0x3c, 0x36, 0x90, 0x10, 0x17,
	0x4e, 0x7e, 0xe2, 0xe7, 0xf7, 0x2f, 0x92, 0x7f, 0x68, 0x2f, 0x97, 0x1c, 0x32, 0x3d, 0x72, 0x47,
	0x54, 0x2a, 0x69, 0x24, 0xbe, 0x7d, 0x5a, 0x25, 0xab, 0xf8, 0x1c, 0x16, 0x91, 0x06, 0x75, 0x26,
	0x12, 0x88, 0xdc, 0xfa, 0xce, 0x7e, 0x2a, 0x53, 0xd9, 0x62, 0x46, 0x76, 0x72, 0x70, 0xfa, 0x12,
	0x05, 0x47, 0x95, 0x59, 0xce, 0xc0, 0x30, 0x3a, 0x45, 0x5b, 0x33, 0x30, 0x4b, 0xc9, 0x71, 0x0f,
	0x6d, 0x2e, 0x98, 0x16, 0x49, 0xe8, 0xe1, 0x5d, 0xd4, 0xd3, 0x22, 0x2d, 0x98, 0xa9, 0x14, 0x84,
	0xbe, 0xdd, 0x18, 0xb9, 0x82, 0x22, 0xec, 0xe0, 0x3d, 0xf4, 0x5f, 0x3b, 0xc6, 0x37, 0xfb, 0x0d,
	0x3a, 0x40, 0xc1, 0x5c, 0x66, 0xd0, 0xea, 0xdd, 0x45, 0xdd, 0x93, 0xba, 0x04, 0x1c, 0xa0, 0x6e,
	0xa5, 0x41, 0x85, 0x1e, 0x46, 0x68, 0x4b, 0xd7, 0xda, 0x40, 0x1e, 0xfa, 0xf4, 0x1d, 0x0a, 0xde,
	0x68, 0x50, 0x2d, 0xf2, 0x18, 0x21, 0x3b, 0xbf, 0x36, 0xcc, 0x54, 0xda, 0xa2, 0x0a, 0xa9, 0x72,
	0x96, 0x85, 0x1e, 0xde, 0x41, 0x01, 0x17, 0x9a, 0x2d, 0x32, 0xe0, 0xa1, 0x8f, 0xff, 0x47, 0xbb,
	0x56, 0x29, 0x16, 0x05, 0x4b, 0x8c, 0x38, 0x83, 0xb0, 0x83, 0xf7, 0x51, 0x58, 0x32, 0xad, 0xcf,
	0xa5, 0xe2, 0x31, 0x7c, 0x28, 0x85, 0x02, 0x1e, 0x76, 0xe9, 0xf7, 0x0d, 0xb4, 0x39, 0xb3, 0xff,
	0x8d, 0x5f, 0xa0, 0x8e, 0xe0, 0x07, 0x7e, 0xdf, 0x1f, 0xf4, 0xa6, 0x93, 0x75, 0x43, 0x3a, 0x82,
	0x5f, 0x36, 0xe4, 0xd1, 0x19, 0xcb, 0x04, 0x1f, 0x53, 0x05, 0xef, 0x2b, 0x4b, 0xa1, 0xfd, 0x54,
	0xaa, 0x7c, 0x4c, 0x4b, 0x25, 0x72, 0xa6, 0xea, 0x78, 0x05, 0xf5, 0xc4, 0xd4, 0x25, 0x8c, 0x93,
	0x25, 0x53, 0x83, 0xc3, 0xc7, 0x0f, 0xe8, 0xbc, 0x23, 0x38, 0xae, 0xd0, 0x76, 0xa2, 0x80, 0x19,
	0x88, 0x8d, 0xc8, 0xe1, 0xa0, 0xd3, 0xaa, 0x9e, 0x7c, 0x69, 0x88, 0xf7, 0xad, 0x21, 0x3d, 0x7b,
	0x17, 0x9d, 0x88, 0x1c, 0xd6, 0x0d, 0xd9, 0x77, 0x38, 0xfb, 0xf5, 0x50, 0xe6, 0xc2, 0x40, 0x5e,
	0x9a, 0xfa, 0xb2, 0x21, 0xf7, 0x9d, 0x4f, 0xab, 0xcd, 0x99, 0x01, 0xcb, 0x99, 0x14, 0xd2, 0xf4,
	0x8b, 0x2a, 0xcb, 0x26, 0xd7, 0x48, 0x3a, 0x47, 0x37, 0x02, 0xd6, 0xb6, 0x2a, 0xf9, 0xb5, 0xed,
	0xc6, 0x5f, 0x6c, 0x1d, 0xee, 0x1f, 0x6c, 0x6f, 0x04, 0xf0, 0x53, 0xd4, 0x13, 0x3a, 0xe6, 0x90,
	0x81, 0x81, 0x83, 0x6e, 0xdf, 0x1f, 0x04, 0x53, 0xba, 0x6e, 0x08, 0x16, 0xfa, 0x59, 0x7b, 0xf7,
	0x9b, 0x43, 0xe0, 0x1c, 0x86, 0x74, 0x1e, 0xfc, 0xdc, 0xe3, 0x53, 0xb4, 0xed, 0xd8, 0x2e, 0xf7,
	0x66, 0x9b, 0xfb, 0xf9, 0x55, 0xee, 0x5b, 0x96, 0x10, 0x09, 0xfb, 0x1a, 0x55, 0x1e, 0x39, 0x06,
	0x3f, 0x32, 0xeb, 0x86, 0xf8, 0xc3, 0xcb, 0x86, 0xdc, 0xfb, 0x53, 0xe2, 0x5f, 0x83, 0x3a, 0x65,
	0x1b, 0x74, 0xbc, 0xf3, 0xf5, 0x33, 0xf1, 0x3e, 0x5e, 0x10, 0xef, 0xd3, 0x05, 0xf1, 0xa6, 0x93,
	0xb7, 0x4f, 0x52, 0x61, 0x96, 0xd5, 0x22, 0x4a, 0x64, 0x3e, 0x9a, 0x89, 0x44, 0xc9, 0xe3, 0x52,
	0x0f, 0x93, 0x62, 0x64, 0xab, 0x31, 0x3c, 0x87, 0xc5, 0xa8, 0x5c, 0xa5, 0xa3, 0xab, 0x7a, 0x5c,
	0xb5, 0x67, 0xe2, 0x8e, 0x57, 0xde, 0x62, 0xab, 0x2d, 0xc6, 0xe1, 0x8f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x6d, 0x89, 0x71, 0x76, 0x5e, 0x03, 0x00, 0x00,
}
